### ISSUE TITLE
Milestone 4 To-do List

### ISSUE THREAD

**Issue by shoebillm** [UBC-MDS/reasytries#23]
**GitHub actions workflow for continuous integration**

- [x] Add continuous integration workflows using for running R CMD check (results to [codecov](https://codecov.io/)
- [x] `usethis` package functions to add:
    * [check-standard](https://github.com/r-lib/actions/blob/master/.github/workflows/check-standard.yaml)
    * [test-coverage](https://github.com/r-lib/actions/blob/master/.github/workflows/test-coverage.yaml)

**Documentation**

- [x] Use [vignette](https://r-pkgs.org/vignettes.html#vignettes) package-wide documentation + [pkgdown](https://pkgdown.r-lib.org/) R package to set up a website for the package
- [x] Include a full usage demonstration of all package functions (runnable)
- [x] Include installation instructions in the `README.Rmd` file
- [x] examine `Roxygen2` documentation of the functions 

**License checklist**

- [x] Discuss and reason the license choice by opening issues in both Python and R repositories

**Initiate a package review request**

- [x] Open an issue per package in [MDS software review](https://github.com/UBC-MDS/software-review-2021)
    * [R template](https://devguide.ropensci.org/reviewrequesttemplate.html)
    * [Python template](https://github.com/pyOpenSci/software-review/issues/new/choose)

**Submission instructions**

- [x] The URL for each of your your public projects' repositories (X2)
- [x] The URL to a release for each of your projects' repositories (X2)
- [x] The URL to the issue that thoroughly discusses and reasons the license choice (X1 or X2)

**Comment by rainbowxyt0305** [comment]
Done all items!
